### ISSUE TITLE
Unable to click on the file path navigation links just under the search box

### ISSUE THREAD

**Issue by aawc** [kalman/chrome-extensions#3]
For insance, open https://code.google.com/p/chromium/codesearch#chromium/src/components/safe_json/&q=safe&sq=package:chromium&

And then try to click any of the directory links in:
//src/components/safe_json/

The problem is that the following div is too big and appears on top of the filepath:
<div class="m-e sandbar" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px;">

Its height is set to 60px by .m-e in CSS, but since OmniChromium removes the Chromium icon next to search, this height should also be reduced.

**Comment by aawc** [comment]
PR: https://github.com/kalman/chrome-extensions/pull/4

**Comment by aawc** [comment]
Fixed by #5

**Comment by kalman** [comment]
Thanks!
